apiVersion: v1
kind: ConfigMap
metadata:
  name: k8spipeline-deployer-config
data:
  # your custom resource groupname
  RESOURCE_GROUP: "controllers.k8spipeline.io"

  # your custom resource name (plural)
  RESOURCE_NAME: "k8sdeploytemplates"

  # default api version of your custom resource
  API_VERSION: "v1"

  # default docker container registry
  DOCKER_REGISTRY: "{{ .Values.deployController.dockerRegistry  }}"

  # default custom resource namespace
  RESOURCE_NAMESPACE: "{{ .Release.Namespace }}"

  # git repo url for template config files
  CONFIG_REPO_URL: "{{ .Values.deployController.configGitRepository }}"

  # repo sync interval (in seconds)
  SYNC_INTERVAL: "{{ .Values.deployController.repoSyncInterval }}"