apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: k8sdeploytemplates.controllers.k8spipeline.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: controllers.k8spipeline.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by the Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                templateVariables:
                  type: string
                configsToUse:
                  type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: k8sdeploytemplates
    # singular name to be used as an alias on the CLI and also for displaying
    singular: k8sdeploytemplate
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: K8sDeployTemplate
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - k8sdeploytemp