VERSION 0.6
FROM bash:4.4
WORKDIR /setup-arena

web-server:
	# We need an nginx container which can pass requests to our nodejs container,
	# as well as serve any static content.
	FROM hoosin/alpine-nginx-nodejs:latest

	ARG version='0.1'
	ARG docker_registry='drayfocus/earthly-sample'
	ARG service='sample'

	# Create app directory
	WORKDIR /usr/src/app

	## Then copy our app source code into the image
	COPY  ./app .

	## Build app 
	RUN cd /usr/src/app && cd app && npm install --legacy-peer-deps && npm run build

	## Build server
	RUN cd /usr/src/app && cd server && npm install


	EXPOSE 8080
	CMD [ "node", "server/src/server.js" ]

	# We need to add our NGINX template to the container for startup,
	# and configuration.
	COPY ./conf/nginx.conf /etc/nginx/templates/default.conf.template

	SAVE IMAGE --push ${docker_registry}/${service}_web_server:v${version}
