apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8spipeline-mysql-pv
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.persistentVolumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"