apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8spipeline-mysql-pv-claim
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistentVolumeSize }}
