# Default values for k8s-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingressNginx:
  enabled: true

certManager:
  enabled: true

deployController:
  # Specify your docker registery
  dockerRegistry: "docker.io"
  configGitRepository: "https://github.com/Doctordrayfocus/K8sPipelineTemplates.git"
  # Git repository sync interval in seconds
  repoSyncInterval: 3

pipelineApp:
  deploymentReplica: 1
  letsEncryptEmail: "developer@example.com"
  appUrl: "sample.domain.com"
  buildTemplateRepository: "https://github.com/Doctordrayfocus/K8sPipelineTemplates.git"
  # Git repository sync interval in seconds 
  buildTemplateSyncInterval: 100

  # Github config
  githubClientID: ""
  githubClientSecret: ""

  # Bitbucket config
  bitbucketClientID: ""
  bitbuckerClientSecret: ""

  # Gitlab config
  gitlabAppID: ""
  gitlabAppSecret: ""

database:
  persistentVolumeSize: 2Gi
