VERSION 0.6

LARAVELAPP:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dir="./$service/environments/$env"
    ARG file="$dir/app-template.yaml"
	ARG version=0.1
	ARG httpsDomain1=''
	ARG OUTPUT="apiVersion: template.k8spipeline.io/v1
kind: K8sAppTemplate
metadata:
  name: ${service}
spec:
  serviceName: '${service}'
  environment: '${env}'
  deploymentReplicas: 1
  imageVersion: '${version}'
  configsToUse: '${configToUse}'
"
	RUN mkdir -p $dir
    RUN echo "$OUTPUT" > "$file"

CONFIGMAP:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dirExtra="./$service/environments/$env/extras-$service"
    ARG file="$dirExtra/configmap.yaml"
	ARG OUTPUT="apiVersion: v1
kind: ConfigMap
metadata:
  name: ${service}
  namespace: ${env}-${service}
data:
  APP_NAME: 'AppName'
  APP_ENV: 'production'
  APP_DEBUG: 'false'
"
	RUN mkdir -p $dirExtra
    RUN echo "$OUTPUT" > "$file"

SECRETS:
	COMMAND
    ARG service='sample'
    ARG env='prod'
    ARG dirExtra="./$service/environments/$env/extras-$service"
    ARG file="$dirExtra/secrets.yaml"
	ARG OUTPUT="apiVersion: v1
kind: Secret
metadata:
  name: ${service}
  namespace: ${env}-${service}
type: Opaque
stringData:
  APP_KEY: ''
  DB_USERNAME: 
  DB_PASSWORD: ''
"
	RUN mkdir -p $dirExtra
    RUN echo "$OUTPUT" > "$file"
