---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8spipeline-app-config
data:
  PORT: "8080"
  DB_HOST: k8spipeline-mysql.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: "3306"
  DB_USER: root
  NODE_ENV: production
  DB_PASSWORD: password
  DB_DATABASE: k8s_pipeline
  SECRET_KEY: secretKey
  LOG_FORMAT: dev
  LOG_DIR: ../logs
  ORIGIN: "true"
  CREDENTIALS: "true"
  GITHUB_CLIENT_ID: "{{ .Values.pipelineApp.githubClientID }}"
  GITHUB_CLIENT_SECRET: "{{ .Values.pipelineApp.githubClientSecret }}"
  GITLAB_APP_ID: "{{ .Values.pipelineApp.gitlabAppID }}"
  GITLAB_APP_SECRET: "{{ .Values.pipelineApp.gitlabAppSecret }}"
  BITBUCKET_CLIENT_ID: "{{ .Values.pipelineApp.bitbucketClientID }}"
  BITBUCKET_CLIENT_SECRET: "{{ .Values.pipelineApp.bitbuckerClientSecret }}"
  TEMPLATE_CONFIG_REPO_URL: "{{ .Values.pipelineApp.buildTemplateRepository }}"
  TEMPLATE_SYNC_INTERVAL: "{{ .Values.pipelineApp.buildTemplateSyncInterval }}"
  DOCKER_REGISTRY: "{{ .Values.deployController.dockerRegistry }}"
  APP_URL: "{{ .Values.pipelineApp.appUrl }}"
  UPLOAD_URL: "https://{{ .Values.pipelineApp.appUrl }}/save-service-setup"
