---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spipeline-app-webserver
  namespace: {{ .Release.Namespace }}
  labels:
    tier: backend
    layer: webserver
spec:
  replicas: {{ .Values.pipelineApp.deploymentReplica }}
  selector:
    matchLabels:
      tier: backend
      layer: webserver
  template:
    metadata:
      labels:
        tier: backend
        layer: webserver
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-directory
          hostPath:
            path: /var/lib/docker
        - name: buildkitd-temp
          emptyDir: {} # Or other volume type
      containers:
        - name: webserver
          image: drayfocus/k8spipeline-app:0.53
          envFrom:
            - configMapRef:
                name: k8spipeline-app-config
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
            - containerPort: 2368
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
            - mountPath: /tmp/earthly
              name: buildkitd-temp
