apiVersion: v1
kind: Service
metadata:
  name: k8spipeline-app-webserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    tier: backend
    layer: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
